# Generated by Django 2.2 on 2019-05-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='email_id',
        ),
    ]
