# Generated by Django 2.2 on 2019-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190429_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.CharField(max_length=5),
        ),
    ]
