# Generated by Django 2.2 on 2019-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190502_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
