# Generated by Django 2.2 on 2019-05-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', null=True, upload_to='product_images/'),
        ),
    ]
