# Generated by Django 2.2 on 2019-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190523_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='product_images/'),
        ),
    ]
